exclude: docs
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed (500kB)
      - id: check-ast # Simply check whether the files parse as valid python.
      - id: check-byte-order-marker # Forbid files which have a UTF-8 byte-order marker
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types.
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-docstring-first # Checks a common error of defining a docstring after code.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-toml # This hook checks toml files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
        args:
          - --unsafe
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: detect-aws-credentials # Detects *your* aws credentials from the aws cli credentials file
        args:
          - --allow-missing-credentials
      - id: detect-private-key # Detects the presence of private keys
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: forbid-new-submodules # Prevent addition of new git submodules
      - id: mixed-line-ending # Replaces or checks mixed line ending
      # - id: no-commit-to-branch # Don't commit to branch
      - id: trailing-whitespace # This hook trims trailing whitespace.
        args: ["--markdown-linebreak-ext=md"]
  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: &isort_args
          - --line-length=80
          - --profile=black
          - --combine-as
          - --lines-after-imports=2
          - --src-path=app
      - id: isort
        name: isort (cython)
        types: [cython]
        args: *isort_args
      - id: isort
        name: isort (pyi)
        types: [pyi]
        args: *isort_args
  # Black
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4'] # this is for linux dependancy issue, can remove after main repo soleved it.
        args:
          - "-l 100"
  # Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
  # Flake8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=80
          - --extend-ignore=E266
        additional_dependencies:
          - flake8-print
  # pydocstyle
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
          - --add-ignore=D100,D104,D105,D106,D212
          - --add-select=D213,D404,D413
  # Conventional Commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
