# Generated by Django 3.2.13 on 2022-05-22 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodeCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=500)),
                ('last_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.code')),
            ],
        ),
        migrations.CreateModel(
            name='BrandCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=500)),
                ('assigned_to', models.CharField(blank=True, max_length=500, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('AMOUNT', 'Amount')], max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codes.code')),
            ],
        ),
    ]
